/home/Codici/Blink/PowerManager/src/abortExecution.f90 File Reference
terminates the execution in case of error.
Functions/Subroutines
subroutine abortexecution (i, j, line, word, r1, r2, iVec)
abort the program execution.
Detailed Description
aborts the program exectuion in case of error and print the error message
according to the error code given as input.
Author
Andrea Facci.
Definition in file abortExecution.f90.
Function/Subroutine Documentation
subroutine abortexecution (integer, intent(in), optional i, integer, intent(in), optional j, integer, intent(in), optional line, character(len=*), intent(in), optional word, real(kind = prec), intent(in), optional r1, real(kind = prec), intent(in), optional r2, real(kind = prec), dimension(*), intent(in), optional iVec)
aborts the program exectuion in case of error and print the error message according to the error code given as input.
Parameters
in i,j integers that identify the error.
in line integer that identifies the line affected by the mistake in an input file
in word character input to report the mispelled or unexpected sentence
in r1,r2 double precision reals. Useful to report incoherence between plant parameters
Definition at line 42 of file abortExecution.f90.
Referenced by addsection::addboilers(), addsection::addchillers(), addsection::addtrigenerative(), graphtools::allcombin(), checkplant(), strategies::electricaltracking(), strategies::fullload(), graphtools::graphpoints(), graphtools::minpathtopobw(), readboiler(), readchillers(), readelstorage(), readenv(), readgeneral(), readloads(), readpv(), readsc(), readthstorage(), readtrigen(), readwind(), and strategies::thermaltracking().