/home/andrea/Desktop/FortranCodeBW/src/allocateVar.f90 File Reference
variable allocation.
Functions/Subroutines
subroutine allocatevar (what, num)
variable allocation
Detailed Description
Author
Definition in file allocateVar.f90.
Function/Subroutine Documentation
subroutine allocatevar (integer, intent(in) what, integer, intent(in), optional num)
Allocates the veraibles according to the inputs. All the allocation of `global` variables should be done here.
Parameters
in what defines the variables to be allocated
in num defines the dimnesion of the array
Author
Andrea Facci
Definition at line 36 of file allocateVar.f90.
Referenced by buildplant(), readboiler(), readchillers(), readgeneral(), readloads(), and readtrigen().