/home/Progetti/Siat/Ottimizzatore/src/buildPlantRev.f90 File Reference
Functions/Subroutines
subroutine buildplantrev
Collects all the informations relative to the power plant.
Function/Subroutine Documentation
subroutine buildplantrev ()
Collects all the informations relative to the power plant starting from the Inputs of the single machinery. Calculates the efficiencies for each given set-point and store them in a single array. Perform units of measure conversions when necessary.
Author
Definition at line 40 of file buildPlantRev.f90.
References addsection::addboilers(), addsection::addchillers(), addsection::addthermalstorage(), addsection::addtrigenerative(), allocatevar(), checkplant(), deallocatevar(), myarithmetic::rnan(), and timestep().
Referenced by main().