/home/andrea/Desktop/FortranCodeBW/src/buildPlant.f90 File Reference
Collects all the informations relative to the power plant.
Functions/Subroutines
subroutine buildplant
Collects all the informations relative to the power plant.
Detailed Description
Author
Definition in file buildPlant.f90.
Function/Subroutine Documentation
subroutine buildplant ()
Collects all the informations relative to the power plant starting from the Inputs of the single machinery. Calculates the efficiencies for each given set-point and store them in a single array. Perform units of measure conversions when necessary.
Author
Definition at line 40 of file buildPlant.f90.
References allocatevar(), and checkplant().
Referenced by main().