globalresults Module Reference
Public Member Functions
real(kind=prec) function globelrev (setPoint)
Electric energy revenues.
real(kind=prec) function globthrev (setPoint)
thermal energy revenues.
real(kind=prec) function globchrev (setPoint)
Chilling energy revenues.
real(kind=prec) function globfuelcost (setPoint)
Calculates the costs to buy the fuel.
real(kind=prec) function globmaintcost (setPoint)
Calculates the mintenance costs.
real(kind=prec) function globfirecost (setPoint)
Calculates the lighting cost.
real(kind=prec) function globcost (setPoint)
real(kind=prec) function globrevenues (setPoint)
real(kind=prec) function globprofit (setPoint)
real(kind=prec) function globpec (setPoint)
Detailed Description
Author
This module contains the definition of all the procedures that perform global economic and energetic calculation for the whole duration of ths simulation
Author
Definition at line 42 of file globalResults.f90.
Member Function/Subroutine Documentation
real(kind = prec) function globalresults::globchrev (integer, dimension(0:ntime+1, nm), intent(in) setPoint)
Calculates the revenues (in euro or any other currency according to the one used in the input) from chilling energy selling to the various clients.
 R_{ch} = \sum_{clients} U_{ch}(i)c_{ch}(i)dt 
 where $ U_{ch}(i)$ is the power demand (in kW) of the $i$'th client, $c_{ch}(i)$ is the price in euro/kJ of electric energy for each client and $ dt$ is the time-step duration.
Parameters
in c index of the given set-point to be given as input. Defines the state of the plant $sp(i) = sp(c\_(i))$
in t time step index. Note t=x meas the x'th time step from the simulation start.
Author
Andrea Facci
Definition at line 159 of file globalResults.f90.
References economy::chrev().
Referenced by globrevenues(), and output().
real(kind=prec) function globalresults::globcost (integer, dimension(0:ntime+1,nm), intent(in) setPoint)
Definition at line 290 of file globalResults.f90.
References globfirecost(), globfuelcost(), and globmaintcost().
Referenced by globprofit(), and output().
real(kind = prec) function globalresults::globelrev (integer, dimension(0:ntime+1, nm), intent(in) setPoint)
Calculates the revenues (in euro or any other currency according to the one used in the input) from electric energy selling to the various clients and to the grid. Electric energy revenues are calculated in a different way for each kind of grid connection. Specifically:
Stand Alone:
 R_{el} = \sum_{clients} U_{el}(i)c_{el}(i)dt 
 where $ U_{el}(i)$ is the power demand (in kW) of the $i$'th client, $c_{el}(i)$ is the price in euro/kJ of electric energy for each client and $ dt$ is the time-step duration.
Grid connected with net metering:
 R_{el} = \sum_{clients} U_{el}(i)c_{el}(i)dt + P_{el}c_{s_{grid}} - U_{el}^{t}c_{b_{grid}} 
 where $P_{el}$ is the total electric power produced by the power plant, $c_{s_{grid}}$ is the selling price to the grid, $U_{el}^{t} = \sum_{clients} U_{el}(i) + U_{el}^{self} $ is the total electric demand, including the power plant self-consumption $U_{el}^{self}$
Grid Connected without net metering:
 R_{el} = \sum_{clients} U_{el}(i)c_{el}(i)dt + (P_{el} - U_{el}^{t}) c_{grid} 
 where $ c_{grid} = c_{s_{grid}}$ if $P_{el} \ge U_{el}^{t}$ and $ c_{grid} = c_{b_{grid}}$ otherwise
Parameters
in c index of the given set-point to be given as input. Defines the state of the plant $sp(i) = sp(c\_(i))$
in t time step index. Note t=x meas the x'th time step from the simulation start.
Author
Andrea Facci
Definition at line 84 of file globalResults.f90.
References economy::elrev().
Referenced by globrevenues(), and output().
real(kind = prec) function globalresults::globfirecost (integer, dimension(0:ntime+1,nm), intent(in) setPoint)
Calculates the cost associated to each lighting of a machinery.
 C_{l} > 0 \qquad \mbox{if} \qquad sp(t,i) > 0 \;\mbox{and}\; sp(t-1,i) = 0 
 this cost will be added to the operative profit to for the arc profit/cost.
Parameters
in c index of the given set-point to be given as input. Defines the state of the plant $sp(i) = sp(c\_(i))$
in t time step index. Note t=x meas the x'th time step from the simulation start.
Author
Andrea Facci
Definition at line 270 of file globalResults.f90.
References economy::firecost().
Referenced by globcost(), and output().
real(kind = prec) function globalresults::globfuelcost (integer, dimension(0:ntime+1, nm), intent(in) setPoint)
Calculates the costs to buy the fuel (in euro or any other currency according to the one used in the input)
 C_{f} = \sum_{Trig+Boi} \frac{E_{in}(i)c_{f}(i)}{H_i(i)}dt 
 where $c_{f}(i)$ is the specific cost (per unit mass or volume) of the fuel for the $i$'th machine, $H_i(i)$ is the fuel LHV (kJ per unit mass or volume), $E_{in}(i)$ is the primary energy input. $c_{ch}(i)$ is the price in euro/kJ of electric energy for each client and $ dt$ is the time-step duration.
 Note that even though international units are strongly suggested, any units of mass and/or volume is valid for $c_{f}$ and $H_i$ provided that coherence between the units of these two variables is respected. Moreover prices and LVSs may may be expressend in different units for differend machines.
Parameters
in c index of the given set-point to be given as input. Defines the state of the plant $sp(i) = sp(c\_(i))$
in t time step index. Note t=x meas the x'th time step from the simulation start.
Author
Andrea Facci
Definition at line 202 of file globalResults.f90.
References economy::fuelcost().
Referenced by globcost(), and output().
real(kind = prec) function globalresults::globmaintcost (integer, dimension(0:ntime+1, nm), intent(in) setPoint)
Calculates the maintenance costs (in euro or any other currency according to the one used in the input)
 C_{m} = \sum c_{m}(i)dt \qquad \mbox{if}\qquad sp(i) > 0 
 where $c_{m}(i)$ is the maintenance cost per unit time and $ dt$ is the time-step duration.
Parameters
in c index of the given set-point to be given as input. Defines the state of the plant $sp(i) = sp(c\_(i))$
in t time step index. Note t=x meas the x'th time step from the simulation start.
Author
Andrea Facci
Definition at line 237 of file globalResults.f90.
References economy::maintenancecost().
Referenced by globcost(), and output().
real(kind=prec) function globalresults::globpec (integer, dimension(0:ntime+1,nm), intent(in) setPoint)
Definition at line 326 of file globalResults.f90.
References energy::pec(), and energy::pecpenalty().
Referenced by output().
real(kind=prec) function globalresults::globprofit (integer, dimension(0:ntime+1,nm), intent(in) setPoint)
Definition at line 314 of file globalResults.f90.
References globcost(), and globrevenues().
Referenced by output().
real(kind=prec) function globalresults::globrevenues (integer, dimension(0:ntime+1,nm), intent(in) setPoint)
Definition at line 302 of file globalResults.f90.
References globchrev(), globelrev(), and globthrev().
Referenced by globprofit(), and output().
real(kind = prec) function globalresults::globthrev (integer, dimension(0:ntime+1, nm), intent(in) setPoint)
Calculates the revenues (in euro or any other currency according to the one used in the input) from thermal energy selling to the various clients.
 R_{th} = \sum_{clients} U_{th}(i)c_{th}(i)dt 
 where $ U_{th}(i)$ is the power demand (in kW) of the $i$'th client, $c_{th}(i)$ is the price in euro/kJ of electric energy for each client and $ dt$ is the time-step duration.
Parameters
in c index of the given set-point to be given as input. Defines the state of the plant $sp(i) = sp(c\_(i))$
in t time step index. Note t=x meas the x'th time step from the simulation start.
Author
Andrea Facci
Definition at line 121 of file globalResults.f90.
References economy::threv().
Referenced by globrevenues(), and output().
The documentation for this module was generated from the following file:
/home/Progetti/Siat/Ottimizzatore/src/globalResults.f90