euristics Module Reference
Module that contains the function to apply an euristics to the graph.
Public Member Functions
logical function thredundant (c, t)
Rejects solutions with excess of thermal production.
logical function chredundant (c, t)
Rejects solutions with excess of chilling production.
Detailed Description
Module that contains the function to apply an euristics to the graph. in order to reduce the number of points and arcs of the graph.
Author
Andrea Facci
Definition at line 38 of file euristics.f90.
Member Function/Subroutine Documentation
logical function euristics::chredundant (integer, dimension(nm), intent(in) c, integer, intent(in) t)
Rejects the points where an excess chilling production is achieved using mechanical chillers. If there is a constraint on the duration of the on or off intervals the possibility to operate the chillers at minimum load even when not strictly necessary is considered.
Parameters
in c index of the given set-point to be given as input. Defines the state of the plant $sp(i) = sp(c\_(i))$
in t time-step index
Author
Andrea Facci
Definition at line 161 of file euristics.f90.
References energy::chselfcons(), and constr::constraints().
Referenced by graphtools::graphpoints(), and graphtools::graphpointslocalmin().
logical function euristics::thredundant (integer, dimension(nm), intent(in) c, integer, intent(in) t)
Rejects the points where an excess thermal production is achieved using fuel boilers. If there is a constraint on the duration of the on or off intervals the possibility to operate the boilers at minimum load even when not strictly necessary is considered.
Parameters
in c index of the given set-point to be given as input. Defines the state of the plant $sp(i) = sp(c\_(i))$
in t time-step index
Author
Andrea Facci
Definition at line 71 of file euristics.f90.
References energy::cogthprod(), constr::constraints(), and energy::thselfcons().
Referenced by graphtools::graphpoints(), and graphtools::graphpointslocalmin().
The documentation for this module was generated from the following file:
/home/Progetti/Siat/Ottimizzatore/src/euristics.f90