energy Module Reference
module for energy calculations.
Public Member Functions
real(kind=prec) function elprod (c_, t)
Electrical production.
real(kind=prec) function thprod (c_, t)
Thermal production.
real(kind=prec) function chprod (c_, t)
Chilling production.
real(kind=prec) function thselfcons (c_, t)
Internal thermal consumption of the power plant.
real(kind=prec) function elselfcons (c_, t)
Internal electrical consumption of the power plant.
real(kind=prec) function,
*
dimension(nboi+ntrig) fuelcons (c_, t)
Primary energy input.
real(kind=prec) function,
*
dimension(nm) energyinput (c_, t)
Primary energy input.
real(kind=prec) function,
*
dimension(ntrig+nboi) energyexhaust (c_, t)
Energy exhausted by combustions equipment.
real(kind=prec) function limitrecovery (i, valore, t)
Limit the power of an HRSG.
real(kind=prec) function cogthprod (c_, t)
Cogenerative Thermal production.
real(kind=prec) function pec (c, t)
Primary Energy Consumption.
real(kind=prec) function pecpenalty (cNew, cOld, t)
Primary Energy Consumption Penalty at startup.
real(kind=prec) function thstoragelevelupdate (oldLevel, c, t)
Updates the level of thermal storage.
real(kind=prec) function elstoragelevelupdate (oldLevel, c, t)
Updates the level of electrical storage.
real(kind=prec) function tespower (c, t)
Calculates the power from or to the thermal storage.
Detailed Description
This module contains all procedures tu calculate the enrgy fluxes inside the power plant and bertween the power plant and the clients.
Author
Andrea Facci
Definition at line 38 of file energy.f90.
Member Function/Subroutine Documentation
real(kind = prec) function energy::chprod (integer, dimension(nm), intent(in) c_, integer, intent(in) t)
Calculates the chilling production in kW of the whole power plant, for a given set-point Note that only trigeneration machines and Chillers produce chilling power so far. Thus chilling power is:
 P_{ch} = \sum_{Trig} \frac{sp(i)\cdot P_{max}(i)\cdot k_{env}}{\eta_{el}(i,sp(i))\cdot\alpha_{env}}\eta_{ch}(i,sp(i))\cdot\beta_{env} + \sum_{Chi} sp(i)\cdot P_{max}(i)\cdot\vartheta_{env} 
 where $sp(i)$ is the set point of the $i$'th machine, $\eta_{ch}$ and $\eta_{el}$ are the chilling and electrical efficiencies, respectively, and $P_{max}(i)$ is its rated power; f$ k_{env} $, $ {env} $, $ {env} $, and $ {env} $ are the environmental corrections for electrical power and efficiency, chilling efficiency, and chilling power, respectively. \param[in] c_ index of the given set-point to be given as input. Defines the state of the plant $(i) = sp(c_(i))
Definition at line 189 of file energy.f90.
Referenced by constr::constraints(), and output().
real(kind = prec) function energy::cogthprod (integer, dimension(nm), intent(in) c_, integer, intent(in) t)
Calculates the cogenerative Thermal production in kW of the whole power plant, for a given set-point Note that only trigeneration machines and Boilers produce thermal power so far. Thus Thermal power is:
 P_{th} = \sum_{Trig} \frac{sp(i)\cdot P_{max}(i)}{\eta_{el}(i,sp(i))}\eta_{th}(i,sp(i)) + \sum_{HRSG} sp(i)\cdot P_{max}(i) 
 where $sp(i)$ is the set point of the $i$'th machine, $\eta_{th}$ and $\eta_{el}$ are the thermal and electrical efficiencies, respectively, and $P_{max}(i)$ is its rated power.
Parameters
in c_ index of the given set-point to be given as input. Defines the state of the plant $sp(i) = sp(c\_(i))$
in t time index
Author
Andrea Facci
Definition at line 592 of file energy.f90.
References limitrecovery().
Referenced by strategies::electricaltracking(), strategies::fullload(), strategies::thermaltracking(), and euristics::thredundant().
real(kind = prec) function energy::elprod (integer, dimension(nm), intent(in) c_, integer, intent(in) t)
Calculates the electrical production in kW of the whole power plant, for a given set-point Note that only trigeneration machines produce electrical power so far. Thus electrical power is:
 P_{el} = \sum_{Trig} sp(i)\cdot P_{max}(i)\cdot k_{env} 
 where $sp(i)$ is the set point of the $i$'th trigenerative machine and $P_{max}(i)$ is its rated power. $ k_{env} = k_a\cdot k_T \cdot k_p $ is the environmental power correction; and $ k_a$, $ k_t$, and $ k_p$ are the altitude, temperature, and pressure corrections respectively.
Parameters
in c_ index of the given set-point to be given as input. Defines the state of the plant $sp(i) = sp(c\_(i))$
in t time index
Author
Andrea Facci
Definition at line 59 of file energy.f90.
Referenced by economy::elrev(), economy::grideconomy(), output(), and pec().
real(kind = prec) function energy::elselfcons (integer, dimension(nm), intent(in) c_, integer t)
Calculates the electrical self-consumption of the trigeneration plant, that is, the electrical power needed by the mechanical chillers, for a given set-point
 U_{el}^{self} = \sum_{MecChi} \frac{sp(i)\cdot P_{max}(i)\cdot \vartheta_{env}}{\eta_{ch}(i,sp(i))\cdot \beta_{env}} 
 where $sp(i)$ is the set point of the $i$'th machine, $\eta_{ch}$ is the chilling efficiency, and $P_{max}(i)$ is its rated power; $\beta_{env}$ and $\vartheta_{env}$ are the environmental corrections for chilling efficiency, and chilling power, respectively. The summation is extended over the nmber of mechanical chillers.
Parameters
in c_ index of the given set-point to be given as input. Defines the state of the plant $sp(i) = sp(c\_(i))$
in t time index
Author
Andrea Facci
Definition at line 300 of file energy.f90.
Referenced by strategies::electricaltracking(), economy::elrev(), strategies::fullload(), economy::grideconomy(), pec(), and strategies::thermaltracking().
real(kind=prec) function energy::elstoragelevelupdate (real(kind=prec), intent(in) oldLevel, integer, dimension(nm), intent(in) c, integer, intent(in) t)
Updates the state of charge of vthe thermal storage according to old state of charge and present set point.
 SOC_{th}(t) = SOC_{th}(t-1) sp_{th}\cdot P_{max}\eta 
 where $sp(i)$ is the set point of the thermal storage $P_{max}(i)$ is its rated power and $\eta = \eta_{in}$ if $sp \le 0$ and $\eta = \eta_{out}$ if $sp \ge 0$
Parameters
in c_ index of the given set-point to be given as input. Defines the state of the plant $sp(i) = sp(c\_(i))$
in t time index
Author
Andrea Facci
Definition at line 793 of file energy.f90.
Referenced by constr::elstorageconstr(), output(), and graphtools::uptimecalc().
real(kind = prec) function, dimension(ntrig+nboi) energy::energyexhaust (integer, dimension(ntrig+nboi), intent(in) c_, integer, intent(in) t)
Calculates the energy exhausted by trigenerative equipment and fuel boilers.
 E_{exh}(i) = sp(i)\cdot P_{max}(i)\cdot k_{env} \left[\frac{1}{\eta(i,sp(i))\cdot \alpha_{env}} - 1 \right] 
 where $sp(i)$ is the set point of the $i$'th machine, $\eta(i,sp(i)) = \eta_{el}(i,sp(i))$ for trigenerative equipment and $\eta(i,sp(i))=\eta_{th}(i,sp(i))$ for boilers and, and $P_{max}(i)$ is their rated power. $k_{env}$ and $\alpha_{env}$ represent the environmental corrections
Parameters
in c_ index of the given set-point to be given as input. Defines the state of the plant $sp(i) = sp(c\_(i))$
in t time index
Author
Andrea Facci
Definition at line 482 of file energy.f90.
real(kind = prec) function, dimension(nm) energy::energyinput (integer, dimension(nm), intent(in) c_, integer, intent(in) t)
Calculates the primary energy input of the trigeneration plant, for a given set-point
 E_{in}(i) = \frac{sp(i)\cdot P_{max}(i)\cdot k_{env} }{\eta(i,sp(i))\cdot \alpha_{env}} 
 where $sp(i)$ is the set point of the $i$'th machine, $\eta(i,sp(i)) = \eta_{el}(i,sp(i))$ for trigenerative equipment and $\eta(i,sp(i))=\eta_{th}(i,sp(i))$ for boilers and, and $P_{max}(i)$ is their rated power. $k_{env}$ and $\alpha_{env}$ represent the environmental corrections
Parameters
in c_ index of the given set-point to be given as input. Defines the state of the plant $sp(i) = sp(c\_(i))$
in t time index
Author
Andrea Facci
Definition at line 417 of file energy.f90.
Referenced by output(), pec(), and pecpenalty().
real(kind = prec) function, dimension(nboi+ntrig) energy::fuelcons (integer, dimension(nm), intent(in) c_, integer, intent(in) t)
Calculates the eprimary energy input of the trigeneration plant, for a given set-point
 E_{in}(i) = \frac{sp(i)\cdot P_{max}(i)\cdot k_{env}}{\eta(i,sp(i))\cdot \alpha_{env}} 
 where $sp(i)$ is the set point of the $i$'th machine, $\eta(i,sp(i)) = \eta_{el}(i,sp(i))$ for trigenerative equipment and $\eta(i,sp(i))=\eta_{th}(i,sp(i))$ for boilers and, and $P_{max}(i)$ is their rated power. $k_{env}$ and $\alpha_{env}$ represent the environmental corrections for power and efficiency respectively.
Parameters
in c_ index of the given set-point to be given as input. Defines the state of the plant $sp(i) = sp(c\_(i))$
in t time index
Author
Andrea Facci
Definition at line 359 of file energy.f90.
Referenced by economy::fuelcost(), and output().
real(kind = prec) function energy::limitrecovery (integer, intent(in) i, real(kind = prec), intent(in) valore, integer, intent(in) t)
Limit the power of an HRSG according to the maximum input power coming from the topping plant.
Parameters
in i index of the HRSG being considered
in t time index
in valore maximum value of the input energy.
Author
Andrea Facci
Definition at line 533 of file energy.f90.
Referenced by cogthprod(), and thprod().
real(kind=prec) function energy::pec (integer, dimension(nm), intent(in) c, integer, intent(in) t)
This function calculates the primary energy consumption of the power plant according to the relation:
 PEC = dt(t)\sum_{Trig+Boi} \frac{sp(i)dd\cdot P_{max}(i)}{\eta(i,sp(i))}pef_{fuel}(i)) + P_{grid}pef_{grid}dt(t) 
 where $sp(i)$ is the set point of the $i$'th machine, $\eta = \eta_{th}$ for boilers and $\eta = \eta_{el}$ for trigenerative equipments; pef_{fuel}(i) is the primary energy factor relative to the fuels used by the i'th machine. P_{grid} is the electrical power exchanged with the grid and pef_{grid} is its primary energy factor.
Parameters
in c_ index of the given set-point to be given as input. Defines the state of the plant $sp(i) = sp(c\_(i))$
in t time index
Author
Andrea Facci
Definition at line 656 of file energy.f90.
References elprod(), elselfcons(), and energyinput().
Referenced by globalresults::globpec(), objfunction(), and output().
real(kind=prec) function energy::pecpenalty (integer, dimension(nm), intent(in) cNew, integer, dimension(nm), intent(in) cOld, integer, intent(in) t)
This function calculates the primary energy consumption penalty at
Parameters
in c_ index of the given set-point to be given as input. Defines the state of the plant $sp(i) = sp(c\_(i))$
in t time index
Author
Andrea Facci
Definition at line 697 of file energy.f90.
References energyinput().
Referenced by globalresults::globpec(), graphtools::grapharcs(), and output().
real(kind=prec) function energy::tespower (integer, dimension(nm), intent(in) c, integer, intent(in) t)
This function calculates the power from and to the thermal storage system, given the plant set-point vector and the time-step state of charge and present set point.
 P_{tes}(t) = sp_{tes}\cdot P_{max}\eta_{in}\qquad \mbox{ if } \qquad sp_{tes} \le 0 
 P_{tes}(t) = sp_{tes}\cdot P_{max}eta_{out} \qquad\mbox{ if } \qquad sp_{tes} > 0 
 where $sp_{tes}$ is the set point of the thermal storage $P_{max}$ is its rated power and $\eta_{in}$ and $\eta_{out}$ are the input and output efficiencies, respectively.
Parameters
in c_ index of the given set-point to be given as input. Defines the state of the plant $sp(i) = sp(c\_(i))$
in t time index
Author
Andrea Facci
Definition at line 838 of file energy.f90.
Referenced by strategies::fullload().
real(kind = prec) function energy::thprod (integer, dimension(nm), intent(in) c_, integer, intent(in) t)
Calculates the Thermal production in kW of the whole power plant, for a given set-point Note that only trigeneration machines and Boilers produce thermal power so far. Thus Thermal power is:
 P_{th} = \sum_{Trig} \frac{sp(i)\cdot P_{max}(i)\cdot k_{env}}{\eta_{el}(i,sp(i))\cdot \alpha_{env}}\eta_{th}(i,sp(i))\cdot\gamma_{env}+ \sum_{Boi} sp(i)\cdot P_{max}(i)\cdot \lambda_{env} 
 where $sp(i)$ is the set point of the $i$'th machine, $\eta_{th}$ and $\eta_{el}$ are the thermal and electrical efficiencies, respectively, and $P_{max}(i)$ is its rated power; $ k_{env} $, $ \alpha_{env} $, $ \gamma_{env} $, and $ \lambda_{env} $ are the environmental corrections for electrical power and efficiency, thermal efficiency, and thermal power, respectively.
Parameters
in c_ index of the given set-point to be given as input. Defines the state of the plant $sp(i) = sp(c\_(i))$
in t time index
Author
Andrea Facci
Definition at line 112 of file energy.f90.
References limitrecovery().
Referenced by constr::constraints(), strategies::electricaltracking(), output(), and strategies::thermaltracking().
real(kind = prec) function energy::thselfcons (integer, dimension(nm), intent(in) c_, integer, intent(in) t)
Calculates the thermal self-consumption of the trigeneration plant, that is, hte thermal power needed by the absorbtion chillers.
 U_{th}^{self} = \sum_{AbsChi} \frac{sp(i)\cdot P_{max}(i)\cdot \vartheta_{env}}{\eta_{ch}(i,sp(i))\cdot \beta_{env}} 
 where $sp(i)$ is the set point of the $i$'th machine, $\eta_{ch}$ is the chilling efficiency, and $P_{max}(i)$ is its rated power; $\beta_{env}$ and $\vartheta_{env}$ are the environmental corrections for chilling efficiency, and chilling power, respectively.
Parameters
in c_ index of the given set-point to be given as input. Defines the state of the plant $sp(i) = sp(c\_(i))$
in t time index
Author
Andrea Facci
Definition at line 242 of file energy.f90.
Referenced by constr::constraints(), strategies::electricaltracking(), strategies::fullload(), strategies::thermaltracking(), and euristics::thredundant().
real(kind=prec) function energy::thstoragelevelupdate (real(kind=prec), intent(in) oldLevel, integer, dimension(nm), intent(in) c, integer, intent(in) t)
Updates the state of charge of the thermal storage according to old state of charge and present set point.
 SOC_{th}(t) = SOC_{th}(t-1) sp_{th}\cdot P_{max}\eta 
 where $sp(i)$ is the set point of the thermal storage $P_{max}(i)$ is its rated power and $\eta = \eta_{in}$ if $sp \le 0$ and $\eta = \eta_{out}$ if $sp \ge 0$
Parameters
in c_ index of the given set-point to be given as input. Defines the state of the plant $sp(i) = sp(c\_(i))$
in t time index
Author
Andrea Facci
Definition at line 749 of file energy.f90.
Referenced by strategies::fullload(), output(), constr::thstorageconstr(), and graphtools::uptimecalc().
The documentation for this module was generated from the following file:
/home/Codici/Blink/PowerManager/src/energy.f90