graphtools Module Reference
Data Types
interface objFunction
Public Member Functions
subroutine allcombin (icm, dcm, imax, m, targ)
Generates all the combinations of the set points, staring from the set-point vectors that are stored in the columns of `cm`.
subroutine graphpoints
Generates the graph vetexes, starting from the array of the set-point combinations.
subroutine grapharcs
Generates the grapsh arcs.
subroutine minpathtopofw (ottLoad, minCost)
Miniumum path detemination.
subroutine minpathtopobw (ottLoad, minCost, upTime, minPath)
Miniumum path detemination.
real(kind=prec) function,
*
dimension(2 *nm0+2) uptimecalc (upT, c, t)
Public Attributes
integer ncomb
integer given
integer, dimension(:,:),
*
allocatable comb
integer, dimension(:,:),
*
allocatable indexes
real(kind=prec), dimension(:,:),
*
allocatable spval
real(kind=prec), dimension(:,:),
*
allocatable valiues
Detailed Description
Definition at line 34 of file graphTools.f90.
Member Function/Subroutine Documentation
subroutine graphtools::allcombin (integer, dimension(maxval(imax),m), intent(in), optional icm, real(kind = prec), dimension(maxval(imax),m), intent(in), optional dcm, integer, dimension(m), intent(in) imax, integer, intent(in) m, character(len=*), intent(in), optional targ)
Generates all the combinations of the set points, staring from the set-point vectors that are stored in the columns of `cm`. Each row of the array `comb` represents a set-point of the plant. The total number of states of the plant is also returned in the variable `nComb`
Author
Andrea Facci
Definition at line 130 of file graphTools.f90.
References abortexecution(), and myarithmetic::rnan().
Referenced by main().
subroutine graphtools::grapharcs ()
Generates the grapsh arcs. Note that only vertex relative to consecutive time-steps are connected and that arcs are oriented in the direction of increasing time. Arcs are stored in the form of a predecessor list `predList`, that associates to each node all its predecessors. A weight is assiciated to each element of the predecessor list, equal to the weight of the predecessor vertex plus a cost connected to the variation of state between the actual and predecessor state.
 arcCost(i,j) = pointCost(c(i)) + fireCost(i,j) 
 The number of predecessors for each vertex is asle stored in the `nPre(i)` array.
Definition at line 346 of file graphTools.f90.
References economy::cyclecost(), economy::firecost(), and energy::pecpenalty().
Referenced by main().
subroutine graphtools::graphpoints ()
Generates the graph veteces, starting from the array of the set-point combinations. For each time-step determines which plant state respects the energy (staitc) constraints, and associates them to a graph vertex. A weight, that accounts for the costs/revenues of operating the power plant from time-step t to t+1 at the vertex state, is also calculated for each vertex. The time-step relative to each vertex and the number of verteces for each time step are associated to `pointTime` and `nt` vectors respectively. Vertex 0 will be the starting point of the graph and vertex nPoint + 1 the arriving point
Author
Andrea Facci.
Definition at line 240 of file graphTools.f90.
References abortexecution(), euristics::chredundant(), mathtools::locaterow(), objfunction(), and euristics::thredundant().
Referenced by main().
subroutine graphtools::minpathtopobw (integer, dimension(0:ntime+1,nm), intent(out) ottLoad, real(kind = prec), intent(out) minCost, real(kind = prec), dimension(0:ntime+1,2*nm0 + 2), intent(out) upTime, integer, dimension(0:ntime+1) minPath)
This function determies the minumum path that connects the start point (0) to the arrival point of the graph (nPoint + 1), using backward dynamic programming. Specifically the oprimizazion the algorithm is tailored to sort acyclic graphs with topolgical ordering. Constraints on the duration of operative intervals (on and off states) are considered.
Author
Andrea Facci.
Definition at line 525 of file graphTools.f90.
References abortexecution(), constr::elstorageconstr(), mathtools::locaterow(), constr::thstorageconstr(), constr::timeconstr(), and uptimecalc().
Referenced by main().
subroutine graphtools::minpathtopofw (integer, dimension(0:ntime+1,nm), intent(out) ottLoad, real(kind = prec), intent(out) minCost)
This function determies the minumum path that connects the start point (0) to the arrival point of the graph (nPoint + 1), using dynamic programming. Specifically the oprimizazion the algorithm is tailored to sort acyclic graphs with topolgical ordering.
Author
Andrea Facci.
Definition at line 466 of file graphTools.f90.
Referenced by main().
real(kind = prec) function, dimension(2*nm0 + 2) graphtools::uptimecalc (real(kind = prec), dimension(2*nm0 + 2) upT, integer, dimension(nm), intent(in) c, integer, intent(in) t)
Definition at line 618 of file graphTools.f90.
References energy::elstoragelevelupdate(), and energy::thstoragelevelupdate().
Referenced by minpathtopobw().
Member Data Documentation
integer, dimension(:,:), allocatable graphtools::comb
Definition at line 42 of file graphTools.f90.
integer graphtools::given
Definition at line 40 of file graphTools.f90.
integer, dimension(:,:), allocatable graphtools::indexes
Definition at line 42 of file graphTools.f90.
integer graphtools::ncomb
Definition at line 40 of file graphTools.f90.
real(kind = prec), dimension(:,:), allocatable graphtools::spval
Definition at line 43 of file graphTools.f90.
real(kind = prec), dimension(:,:), allocatable graphtools::valiues
Definition at line 43 of file graphTools.f90.
The documentation for this module was generated from the following file:
/home/Codici/Blink/PowerManager/src/graphTools.f90