myarithmetic Module Reference
Creates and detects NaN.
Public Member Functions
real(kind=prec) function rnan (x)
Creates NaN.
integer function inan (x)
Creates NaN.
logical function isnan (x)
Detects NaNs.
Detailed Description
This module collects some subroutine useful to create and detect NaNs. It trys to imitate the IEEE_ARITHMETIC module that unfortunately is still not available for the gfortran compiler.
Author
Definition at line 36 of file myArithmetic.f90.
Member Function/Subroutine Documentation
integer function myarithmetic::inan (integer, intent(in) x)
Creates a NaN to be associated to an integer, variable.
Parameters
in x random integer number.
Author
Andrea Facci.
Definition at line 61 of file myArithmetic.f90.
logical function myarithmetic::isnan (x)
This subroutine determine if a value is NaN.
Parameters
in x the value to be tested.
Author
Andrea Facci
Definition at line 72 of file myArithmetic.f90.
real(kind = prec) function myarithmetic::rnan (real(kind = prec), intent(in) x)
Creates a NaN to be associated to a real, double precition variable.
Parameters
in x random double precision number.
Author
Andrea Facci.
Definition at line 47 of file myArithmetic.f90.
Referenced by graphtools::allcombin(), buildplantrev(), readboiler(), readchillers(), readenv(), and readtrigen().
The documentation for this module was generated from the following file:
/home/Progetti/Siat/Ottimizzatore/src/myArithmetic.f90