strategies Module Reference
Rule-based strategies.
Public Member Functions
integer function, dimension(0:ntime+1,
*
nm) thermaltracking ()
integer function, dimension(0:ntime+1,
*
nm) electricaltracking ()
integer function, dimension(0:ntime+1,
*
nm) fullload ()
Detailed Description
This module contains all procedures to define the plant behavior under rule-based regulation strategies. Thermal tracking, electrical tracking and full load are considered.
Author
Andrea Facci
Definition at line 38 of file strategies.f90.
Member Function/Subroutine Documentation
integer function, dimension(0:ntime+1,nm) strategies::electricaltracking ()
Definition at line 97 of file strategies.f90.
References abortexecution(), energy::cogthprod(), energy::elselfcons(), getsetpoint::getspboi(), getsetpoint::getspchi(), getsetpoint::getsptrig(), mathtools::locaterow(), energy::thprod(), and energy::thselfcons().
integer function, dimension(0:ntime+1,nm) strategies::fullload ()
Definition at line 144 of file strategies.f90.
References abortexecution(), energy::cogthprod(), getsetpoint::getspboi(), getsetpoint::getspchi(), getsetpoint::getsptes(), mathtools::locaterow(), energy::tespower(), energy::thselfcons(), energy::thstoragelevelupdate(), and getsetpoint::thstoragepmax().
integer function, dimension(0:ntime+1,nm) strategies::thermaltracking ()
Definition at line 51 of file strategies.f90.
References abortexecution(), energy::cogthprod(), energy::elselfcons(), getsetpoint::getspboi(), getsetpoint::getspchi(), getsetpoint::getsptrig(), mathtools::locaterow(), energy::thprod(), and energy::thselfcons().
The documentation for this module was generated from the following file:
/home/Progetti/Siat/Ottimizzatore/src/strategies.f90