getsetpoint Module Reference
Public Member Functions
integer function, dimension(nboi) getspboi (Heat_, t)
integer function, dimension(nchi) getspchi (Cold_, hlimit_, t)
integer function, dimension(ntrig) getsptrig (Power_, Heat_, Cold_, t)
integer function getsptes (Heat_, t)
real(kind=prec) function,
*
dimension(2) thstoragepmax (oldLevel, t, fcon)
Detailed Description
Definition at line 32 of file getSetPoint.f90.
Member Function/Subroutine Documentation
integer function, dimension(nboi) getsetpoint::getspboi (real(kind=prec), intent(in) Heat_, integer, intent(in) t)
Definition at line 42 of file getSetPoint.f90.
Referenced by strategies::electricaltracking(), strategies::fullload(), and strategies::thermaltracking().
integer function, dimension(nchi) getsetpoint::getspchi (real(kind=prec), intent(in) Cold_, real(kind=prec), intent(in), optional hlimit_, integer, intent(in) t)
Definition at line 87 of file getSetPoint.f90.
Referenced by strategies::electricaltracking(), strategies::fullload(), and strategies::thermaltracking().
integer function getsetpoint::getsptes (real(kind=prec), intent(in) Heat_, integer, intent(in) t)
Definition at line 316 of file getSetPoint.f90.
Referenced by strategies::fullload().
integer function, dimension(ntrig) getsetpoint::getsptrig (real(kind=prec), intent(in), optional Power_, real(kind=prec), intent(in), optional Heat_, real(kind=prec), intent(in), optional Cold_, integer, intent(in) t)
Definition at line 172 of file getSetPoint.f90.
Referenced by strategies::electricaltracking(), and strategies::thermaltracking().
real(kind=prec) function, dimension(2) getsetpoint::thstoragepmax (real(kind=prec), intent(in) oldLevel, integer, intent(in) t, logical, intent(in) fcon)
Definition at line 374 of file getSetPoint.f90.
References constr::thstorageconstr().
Referenced by strategies::fullload().
The documentation for this module was generated from the following file:
/home/Progetti/Siat/Ottimizzatore/src/getSetPoint.f90