mathtools Module Reference
Collection of interfaces for basic mathematical tools.
Data Types
interface interpolation
interface scalarInterp
Public Member Functions
integer function locaterow (row, mat, n, m, error)
integer function locateelement (val, vec, n, error)
Detailed Description
Collection of interfaces for basic mathematical tools.
Author
Andrea Facci.
Definition at line 36 of file mathTools.f90.
Member Function/Subroutine Documentation
integer function mathtools::locateelement (real(kind = prec), intent(in) val, real(kind = prec), dimension(n), intent(in) vec, integer, intent(in) n, logical, intent(out), optional error)
Definition at line 122 of file mathTools.f90.
References test().
integer function mathtools::locaterow (real(kind = prec), dimension(n), intent(in) row, real(kind = prec), dimension(m,n), intent(in) mat, integer, intent(in) n, integer, intent(in) m, logical, intent(out), optional error)
Definition at line 67 of file mathTools.f90.
References test().
Referenced by strategies::electricaltracking(), strategies::fullload(), graphtools::graphpoints(), graphtools::minpathtopobw(), and strategies::thermaltracking().
The documentation for this module was generated from the following file:
/home/Codici/Blink/PowerManager/src/mathTools.f90