economy Module Reference
Public Member Functions
real(kind=prec) function elrev (c, t)
Electric energy revenues.
real(kind=prec) function threv (t)
thermal energy revenues.
real(kind=prec) function chrev (t)
Chilling energy revenues.
real(kind=prec) function fuelcost (c, t)
Calculates the costs to buy the fuel.
real(kind=prec) function maintenancecost (c, t)
Calculates the mintenance costs.
real(kind=prec) function currcost (c, t)
Calculates the profit during a time step.
real(kind=prec) function firecost (cNew, cOld)
Calculates the lighting cost.
real(kind=prec) function,
*
dimension(2) grideconomy (c, t)
real(kind=prec) function cyclecost (cNew, cOld)
Calculates the cost associated to each battery charge cycle.
Detailed Description
Author
This module contains the definition of all the procedures that perform economic calculations for a give set-point and time-step, that are, fuel costs, O&M costs, and the revenues from thermal, electric, and chilling, energy selling.
Author
Definition at line 44 of file economy.f90.
Member Function/Subroutine Documentation
real(kind = prec) function economy::chrev (integer, intent(in) t)
Calculates the revenues (in euro or any other currency according to the one used in the input) from chilling energy selling to the various clients.
 R_{ch} = \sum_{clients} U_{ch}(i)c_{ch}(i)dt 
 where $ U_{ch}(i)$ is the power demand (in kW) of the $i$'th client, $c_{ch}(i)$ is the price in euro/kJ of electric energy for each client and $ dt$ is the time-step duration.
Parameters
in c index of the given set-point to be given as input. Defines the state of the plant $sp(i) = sp(c\_(i))$
in t time step index. Note t=x meas the x'th time step from the simulation start.
Author
Andrea Facci
Definition at line 198 of file economy.f90.
Referenced by currcost(), and globalresults::globchrev().
real(kind = prec) function economy::currcost (integer, dimension(nm), intent(in) c, integer, intent(in) t)
Calculates the profit of a time-step(in euro or any other currency according to the one used in the input) for a given set-point, all the costs, except for the costs associated to equipment ignition.
 G = R_{el} + R_{th} + R_{ch} + C_{f} + C_{m} 
 where
$R_{el}$ are the electrical revenues;
$R_{th}$ are the thermal revenues;
$R_{ch}$ are the chilling revenues
$C_{f}$ are the fuel costs;
$C_{m}$ are the maintenance costs;
$ dt$ is the time-step duration.
 Having discarded lighting costs, this profit depends only on the state of the plant at a determined time-step and not on the state at pre previous or subsequent time-step and will be associated to a vertex of the graph.
Parameters
in c index of the given set-point to be given as input. Defines the state of the plant $sp(i) = sp(c\_(i))$
in t time step index. Note t=x meas the x'th time step from the simulation start.
Author
Andrea Facci
Definition at line 333 of file economy.f90.
References chrev(), elrev(), fuelcost(), maintenancecost(), and threv().
Referenced by objfunction().
real(kind = prec) function economy::cyclecost (integer, dimension(nm), intent(in) cNew, integer, dimension(nm), intent(in) cOld)
Calculates the cost associated to each battery charge cycle.
 C_{l} > 0 \qquad \mbox{if} \qquad sp(t,i) > 0 \;\mbox{and}\; sp(t-1,i) = 0 
 this cost will be added to the operative profit to for the arc profit/cost.
Parameters
in c index of the given set-point to be given as input. Defines the state of the plant $sp(i) = sp(c\_(i))$
in t time step index. Note t=x meas the x'th time step from the simulation start.
Author
Andrea Facci
Definition at line 461 of file economy.f90.
Referenced by graphtools::grapharcs().
real(kind = prec) function economy::elrev (integer, dimension(nm), intent(in) c, integer, intent(in) t)
Calculates the revenues (in euro or any other currency according to the one used in the input) from electric energy selling to the various clients and to the grid. Electric energy revenues are calculated in a different way for each kind of grid connection. Specifically:
Stand Alone:
 R_{el} = \sum_{clients} U_{el}(i)c_{el}(i)dt 
 where $ U_{el}(i)$ is the power demand (in kW) of the $i$'th client, $c_{el}(i)$ is the price in euro/kJ of electric energy for each client and $ dt$ is the time-step duration.
Grid connected with net metering:
 R_{el} = \sum_{clients} U_{el}(i)c_{el}(i)dt + P_{el}c_{s_{grid}} - U_{el}^{t}c_{b_{grid}} 
 where $P_{el}$ is the total electric power produced by the power plant, $c_{s_{grid}}$ is the selling price to the grid, $U_{el}^{t} = \sum_{clients} U_{el}(i) + U_{el}^{self} $ is the total electric demand, including the power plant self-consumption $U_{el}^{self}$
Grid Connected without net metering:
 R_{el} = \sum_{clients} U_{el}(i)c_{el}(i)dt + (P_{el} - U_{el}^{t}) c_{grid} 
 where $ c_{grid} = c_{s_{grid}}$ if $P_{el} \ge U_{el}^{t}$ and $ c_{grid} = c_{b_{grid}}$ otherwise
Parameters
in c index of the given set-point to be given as input. Defines the state of the plant $sp(i) = sp(c\_(i))$
in t time step index. Note t=x meas the x'th time step from the simulation start.
Author
Andrea Facci
Definition at line 80 of file economy.f90.
References energy::elprod(), and energy::elselfcons().
Referenced by currcost(), and globalresults::globelrev().
real(kind = prec) function economy::firecost (integer, dimension(nm), intent(in) cNew, integer, dimension(nm), intent(in) cOld)
Calculates the cost associated to each lighting of a machinery.
 C_{l} > 0 \qquad \mbox{if} \qquad sp(t,i) > 0 \;\mbox{and}\; sp(t-1,i) = 0 
 this cost will be added to the operative profit to for the arc profit/cost.
Parameters
in c index of the given set-point to be given as input. Defines the state of the plant $sp(i) = sp(c\_(i))$
in t time step index. Note t=x meas the x'th time step from the simulation start.
Author
Andrea Facci
Definition at line 366 of file economy.f90.
Referenced by globalresults::globfirecost(), graphtools::grapharcs(), and output().
real(kind = prec) function economy::fuelcost (integer, dimension(nm), intent(in) c, integer, intent(in) t)
Calculates the costs to buy the fuel (in euro or any other currency according to the one used in the input)
 C_{f} = \sum_{Trig+Boi} \frac{E_{in}(i)c_{f}(i)}{H_i(i)}dt 
 where $c_{f}(i)$ is the specific cost (per unit mass or volume) of the fuel for the $i$'th machine, $H_i(i)$ is the fuel LHV (kJ per unit mass or volume), $E_{in}(i)$ is the primary energy input. $c_{ch}(i)$ is the price in euro/kJ of electric energy for each client and $ dt$ is the time-step duration.
 Note that even though international units are strongly suggested, any units of mass and/or volume is valid for $c_{f}$ and $H_i$ provided that coherence between the units of these two variables is respected. Moreover prices and LVSs may may be expressend in different units for differend machines.
Parameters
in c index of the given set-point to be given as input. Defines the state of the plant $sp(i) = sp(c\_(i))$
in t time step index. Note t=x meas the x'th time step from the simulation start.
Author
Andrea Facci
Definition at line 244 of file economy.f90.
References energy::fuelcons().
Referenced by currcost(), globalresults::globfuelcost(), and output().
real(kind = prec) function, dimension(2) economy::grideconomy (integer, dimension(nm), intent(in) c, integer, intent(in) t)
Definition at line 391 of file economy.f90.
References energy::elprod(), and energy::elselfcons().
Referenced by output().
real(kind = prec) function economy::maintenancecost (integer, dimension(nm), intent(in) c, integer, intent(in) t)
Calculates the maintenance costs (in euro or any other currency according to the one used in the input)
 C_{m} = \sum c_{m}(i)dt \qquad \mbox{if}\qquad sp(i) > 0 
 where $c_{m}(i)$ is the maintenance cost per unit time and $ dt$ is the time-step duration.
Parameters
in c index of the given set-point to be given as input. Defines the state of the plant $sp(i) = sp(c\_(i))$
in t time step index. Note t=x meas the x'th time step from the simulation start.
Author
Andrea Facci
Definition at line 287 of file economy.f90.
Referenced by currcost(), globalresults::globmaintcost(), and output().
real(kind = prec) function economy::threv (integer, intent(in) t)
Calculates the revenues (in euro or any other currency according to the one used in the input) from thermal energy selling to the various clients.
 R_{th} = \sum_{clients} U_{th}(i)c_{th}(i)dt 
 where $ U_{th}(i)$ is the power demand (in kW) of the $i$'th client, $c_{th}(i)$ is the price in euro/kJ of electric energy for each client and $ dt$ is the time-step duration.
Parameters
in c index of the given set-point to be given as input. Defines the state of the plant $sp(i) = sp(c\_(i))$
in t time step index. Note t=x meas the x'th time step from the simulation start.
Author
Andrea Facci
Definition at line 158 of file economy.f90.
Referenced by currcost(), and globalresults::globthrev().
The documentation for this module was generated from the following file:
/home/Codici/Blink/PowerManager/src/economy.f90