sun Module Reference
Public Member Functions
real(kind=prec) function,
*
dimension(ntime) photo ()
subroutine liujordan
subroutine astronomy
real(kind=prec) function,
*
dimension(ntime) thermalcollector ()
Detailed Description
Definition at line 32 of file sun.f90.
Member Function/Subroutine Documentation
subroutine sun::astronomy ()
Definition at line 128 of file sun.f90.
Referenced by photo(), and thermalcollector().
subroutine sun::liujordan ()
Definition at line 93 of file sun.f90.
Referenced by photo(), and thermalcollector().
real(kind=prec) function, dimension(ntime) sun::photo ()
Definition at line 44 of file sun.f90.
References astronomy(), and liujordan().
real(kind=prec) function, dimension(ntime) sun::thermalcollector ()
Definition at line 162 of file sun.f90.
References astronomy(), and liujordan().
The documentation for this module was generated from the following file:
/home/Progetti/Siat/Ottimizzatore/src/sun.f90