constr Module Reference
static constraints
Public Member Functions
logical function constraints (c, t)
logical function timeconstr (cindex, tState)
logical function thstorageconstr (oldLevel, c, t, finalSOC)
logical function elstorageconstr (oldLevel, c, t)
logical function icestorageconstr (oldLevel, c, t, finalSOC)
Detailed Description
This function checks if the plant respects the energy constraints for a given set-point and time-step. The constraints are:
Thermal Power: $ \sum U_{th} + U_{th}^{self} \le \sum P_{th}$
Chilling Power: $ \sum U_{ch} \le \sum P_{ch}$
Electrical Power : $ \sum U_{el} + U_{el}^{self} \le \sum P_{el}$ only if the pant is bnot grid connected
Parameters
in c index of the given set-point to be given as input. Defines the state of the plant $sp(i) = sp(c\_(i))$
in t time step index. Note t=x meas the x'th time step from the
Author
Andrea Facci
Definition at line 47 of file constraints.f90.
Member Function/Subroutine Documentation
logical function constr::constraints (integer, dimension(nm), intent(in) c, integer, intent(in) t)
Definition at line 51 of file constraints.f90.
References energy::chprod(), energy::chselfcons(), energy::thprod(), and energy::thselfcons().
Referenced by euristics::chredundant(), and euristics::thredundant().
logical function constr::elstorageconstr (real(kind=prec), intent(in) oldLevel, integer, dimension(nm), intent(in) c, integer, intent(in) t)
Definition at line 182 of file constraints.f90.
References energy::elstoragelevelupdate().
logical function constr::icestorageconstr (real(kind=prec), intent(in) oldLevel, integer, dimension(nm), intent(in) c, integer, intent(in) t, logical, intent(in), optional finalSOC)
Definition at line 214 of file constraints.f90.
References energy::icestoragelevelupdate().
logical function constr::thstorageconstr (real(kind=prec), intent(in) oldLevel, integer, dimension(nm), intent(in) c, integer, intent(in) t, logical, intent(in), optional finalSOC)
Definition at line 135 of file constraints.f90.
References energy::thstoragelevelupdate().
Referenced by graphtools::minpathtopobw(), and getsetpoint::thstoragepmax().
logical function constr::timeconstr (integer, dimension(nm), intent(in) cindex, real(kind = prec), dimension(2*nm0), intent(in) tState)
Definition at line 99 of file constraints.f90.
Referenced by graphtools::minpathtopobw().
The documentation for this module was generated from the following file:
/home/Progetti/Siat/Ottimizzatore/src/constraints.f90