/home/andrea/Desktop/FortranCodeBW/src/constraints.f90 File Reference
static constraints.
Functions/Subroutines
logical function constraints (c, t)
static constraints
logical function timeconstr (cindex, tState)
Detailed Description
This file contains a subroutine that checks if the plant respects the energy constraints for a given set-point and time-step.
Definition in file constraints.f90.
Function/Subroutine Documentation
logical function constraints (integer, dimension(nm), intent(in) c, integer, intent(in) t)
This function checks if the plant respects the energy constraints for a given set-point and time-step. The constraints are:
Thermal Power: $ \sum U_{th} + U_{th}^{self} \le \sum P_{th}$
Chilling Power: $ \sum U_{ch} \le \sum P_{ch}$
Electrical Power : $ \sum U_{el} + U_{el}^{self} \le \sum P_{el}$ only if the pant is bnot grid connected
Parameters
in c index of the given set-point to be given as input. Defines the state of the plant $sp(i) = sp(c\_(i))$
in t time step index. Note t=x meas the x'th time step from the
Author
Andrea Facci
Definition at line 46 of file constraints.f90.
References energy::chprod(), energy::thprod(), and energy::thselfcons().
logical function timeconstr (integer, dimension(nm), intent(in) cindex, real(kind(1.d0)), dimension(2*nm), intent(in) tState)
Definition at line 73 of file constraints.f90.
Referenced by graphtools::minpathtopobw().