/home/Codici/Blink/FortranCode/src/findEntry.f90 File Reference
Functions/Subroutines
subroutine ifindentry (entry, n, theUnit, rew, valore, isPresent, nRow)
subroutine dfindentry (entry, n, theUnit, rew, valore, isPresent, nRow)
subroutine cfindentry (entry, n, theUnit, rew, valore, isPresent, nRow)
subroutine findentry (entry, theUnit, rew, valore, isPresent, nRow)
Function/Subroutine Documentation
subroutine cfindentry (character(len=100), intent(in) entry, integer, intent(in) n, integer, intent(in) theUnit, logical, intent(in), optional rew, character(len=100), dimension(n), intent(out), optional valore, logical, intent(out), optional isPresent, integer, intent(out), optional nRow)
Definition at line 143 of file findEntry.f90.
References rewunit().
Referenced by readchillers().
subroutine dfindentry (character(len=100), intent(in) entry, integer, intent(in) n, integer, intent(in) theUnit, logical, intent(in), optional rew, real(kind(1.d0)), dimension(n), intent(out), optional valore, logical, intent(out), optional isPresent, integer, intent(out), optional nRow)
Definition at line 88 of file findEntry.f90.
References rewunit().
subroutine findentry (character(len=100), intent(in) entry, integer, intent(in) theUnit, logical, intent(in), optional rew, character(len=100), intent(out), optional valore, logical, intent(out), optional isPresent, integer, intent(out), optional nRow)
Definition at line 198 of file findEntry.f90.
References rewunit().
Referenced by cfindentry(), dfindentry(), ifindentry(), and readloads().
subroutine ifindentry (character(len=100), intent(in) entry, integer, intent(in) n, integer, intent(in) theUnit, logical, intent(in), optional rew, integer, dimension(n), intent(out), optional valore, logical, intent(out), optional isPresent, integer, intent(out), optional nRow)
Definition at line 33 of file findEntry.f90.
References rewunit().
Referenced by readboiler(), readchillers(), and readtrigen().