/home/andrea/Desktop/FortranCodeBW/src/findEntry2.f90 File Reference
Collection of procetures to find a specific entry inside a file.
Functions/Subroutines
subroutine ifindentry (entry, n, theUnit, rew, valore, isPresent, nRow)
Finds an entry with integer value.
subroutine dfindentry (entry, n, theUnit, rew, valore, isPresent, nRow)
Finds an entry with double precision value.
subroutine cfindentry (entry, n, theUnit, rew, valore, isPresent, nRow)
Finds an entry with character value.
subroutine findentry (entry, theUnit, rew, valore, isPresent, nRow)
Finds an entry and returns the vaule as it is.
Detailed Description
Author
Definition in file findEntry2.f90.
Function/Subroutine Documentation
subroutine cfindentry (character(len=100), intent(in) entry, integer, intent(in) n, integer, intent(in) theUnit, logical, intent(in), optional rew, character(len=100), dimension(n), intent(out), optional valore, logical, intent(out), optional isPresent, integer, intent(out), optional nRow)
Use this subroutine to find a specific entry in a file, when an character value is expected. in the value field, that is between the two `|`. The string in the value field is associated to a character array of dimension `n` Optionally it returns also the number of lines from the current cursor position to locate the required entry, and a logical for the precence of the required field. Optionally it is also possible to rewind the file. Note that the maximum length of each element of the `value` vector is 100.
Parameters
in entry the keyword to be located
in n the number of elements expected for the value field
in theUnit the unit corresponding to the file to be searched
in rew wether the unit is to be rewinded or not
out valore the vaule correspondind to keyword that is searched for
out isPresent logical that tells if the entry is present or not
out nRow number of rows needed to located the entry.
Author
Andrea Facci
Definition at line 185 of file findEntry2.f90.
References findentry().
Referenced by readchillers().
subroutine dfindentry (character(len=100), intent(in) entry, integer, intent(in) n, integer, intent(in) theUnit, logical, intent(in), optional rew, real(kind(1.d0)), dimension(n), intent(out), optional valore, logical, intent(out), optional isPresent, integer, intent(out), optional nRow)
Use this subroutine to find a specific entry in a file, when a double precision value is expected. in the value field, that is between the two `|`. The string in the value field is associated to double precision array of dimension `n` Optionally it returns also the number of lines from the current cursor position to locate the required entry, and a logical for the precence of the required field. Optionally it is also possible to rewind the file.
Parameters
in entry the keyword to be located
in n the number of elements expected for the value field
in theUnit the unit corresponding to the file to be searched
in rew wether the unit is to be rewinded or not
out valore the vaule correspondind to keyword that is searched for
out isPresent logical that tells if the entry is present or not
out nRow number of rows needed to located the entry.
Author
Andrea Facci
Definition at line 115 of file findEntry2.f90.
References findentry().
subroutine findentry (character(len=100), intent(in) entry, integer, intent(in) theUnit, logical, intent(in), optional rew, character(len=100), intent(out), optional valore, logical, intent(out), optional isPresent, integer, intent(out), optional nRow)
Use this subroutine to find a specific entry in a file. If given as parameter returns the `value` field, that is the value comprised between the two `|` in the input file. This subroutine does not associate the vaule fied to any array but returns a single strig axactly as it is in the input file. Optionally it returns also the number of lines from the current cursor position to locate the required entry, and a logical for the precence of the required field. Optionally it is also possible to rewind the file.
Parameters
in entry the keyword to be located
in n the number of elements expected for the value field
in theUnit the unit corresponding to the file to be searched
in rew wether the unit is to be rewinded or not
out valore the vaule correspondind to keyword that is searched for
out isPresent logical that tells if the entry is present or not
out nRow number of rows needed to located the entry.
Author
Andrea Facci
Definition at line 253 of file findEntry2.f90.
References rewunit().
Referenced by cfindentry(), dfindentry(), ifindentry(), and readloads().
subroutine ifindentry (character(len=100), intent(in) entry, integer, intent(in) n, integer, intent(in) theUnit, logical, intent(in), optional rew, integer, dimension(n), intent(out), optional valore, logical, intent(out), optional isPresent, integer, intent(out), optional nRow)
Use this subroutine to find a specific entry in a file, when an integer value is expected in the value field, that is between the two `|`. The string in the value field is associated to an integer array of dimension `n` Optionally it returns also the number of lines from the current cursor position to locate the required entry, and a logical for the precence of the required field. Optionally it is also possible to rewind the file.
Parameters
in entry the keyword to be located
in n the number of elements expected for the value field
in theUnit the unit corresponding to the file to be searched
in rew wether the unit is to be rewinded or not
out valore the vaule correspondind to keyword that is searched for
out isPresent logical that tells if the entry is present or not
out nRow number of rows needed to located the entry.
Author
Andrea Facci
Definition at line 47 of file findEntry2.f90.
References findentry().
Referenced by readboiler(), readchillers(), and readtrigen().