/home/Codici/Blink/PowerManager/src/hCount.f90 File Reference
Count the number of elements of a vector in a text file.
Functions/Subroutines
integer function hcount (value_, first_, last_)
Count the number of elements of a vector in a text file.
Detailed Description
Author
Andrea Facci.
Definition in file hCount.f90.
Function/Subroutine Documentation
integer function hcount (character(len=100), intent(in) value_, character(len=1), optional first_, character(len=1), optional last_)
Use This subroutine to determine the length of a vector, that is a series of values encloesd between two delimiters, when reading from text file. The vector must be specified as a single string input (max length=100), while delimiters may be specified as single character input or left to default that is `(` for opening and `)` for closing.
Parameters
in value_ the string containing teh vector whose lenght is to be determined
in first_,last_ sigle character delimiters of the vector (open and close respectively). If not provided `(` ad `)` will be assumed as defaults
Author
Andrea Facci.
Definition at line 43 of file hCount.f90.
Referenced by readboiler(), readchillers(), readgeneral(), readloads(), and readtrigen().