/home/Progetti/Siat/Ottimizzatore/src/interpolation.f90 File Reference
Remaps a discrete scalar field on a given 1d grid.
Functions/Subroutines
real(kind=prec) function,
*
dimension(m) interpolation (xIn, yIn, n, xOut, m, warn)
Remaps a discrete scalar field on a given 1d grid.
real(kind=prec) function scalarinterp (xIn, yIn, n, x, warn)
Detailed Description
Author
Andrea Facci.
Definition in file interpolation.f90.
Function/Subroutine Documentation
real(kind = prec) function, dimension(m) interpolation (real(kind = prec), dimension(n), intent(in) xIn, real(kind = prec), dimension(n), intent(in) yIn, integer, intent(in) n, real(kind = prec), dimension(m), intent(in) xOut, integer, intent(in) m, integer, dimension(2), intent(out), optional warn)
This subroutine takes a discrete scalar field defined over a 1d grid and remaps it on another 1d mesh given as input. If any of the values in the new mesh is outside the range defined by the oiginal grid, values are extrapolated and an optional warning code is returned.
Parameters
in xIn,yIn grid and values of the 1d field to be mapped
in n number of elements of the discrete field (size(xIn))
in xOut 1d grid where the field is sampled
in m number of elements of the interpolation grid (xOut)
out warn warning code.
Author
Andrea Facci.
Definition at line 46 of file interpolation.f90.
real(kind = prec) function scalarinterp (real(kind = prec), dimension(n), intent(in) xIn, real(kind = prec), dimension(n), intent(in) yIn, integer, intent(in) n, real(kind = prec), intent(in) x, integer, dimension(2), intent(out), optional warn)
Definition at line 94 of file interpolation.f90.
Referenced by addsection::addboilers(), addsection::addchillers(), and addsection::addtrigenerative().