/home/Progetti/Siat/Ottimizzatore/src/matrixRead2.f90 File Reference
reads 2D array of values from a file
Functions/Subroutines
real(kind=prec) function,
*
dimension(nline, ncol) dmatrixread (theUnit, nline, ncol, first_, last_)
reads 2D array of double precision values from a file.
integer function, dimension(nline,
*
ncol) imatrixread (theUnit, nline, ncol, first_, last_)
reads 2D array of integer values from a file.
character(len=100) function,
*
dimension(nline, ncol) cmatrixread (theUnit, nline, ncol, first_, last_)
reads 2D array of character values from a file.
character(len=100) function,
*
dimension(nline) matrixread (theUnit, nline, first_, last_)
reads 2D array from a file.
Detailed Description
Collection of procedures to read 2D arrays from files. Each function associates the values to a different data type (integer, double, character). the first letter of the function name indicates the data type.
Author
Andrea Facci.
Definition in file matrixRead2.f90.
Function/Subroutine Documentation
character(len=100) function, dimension(nline,ncol) cmatrixread (integer, intent(in) theUnit, integer, intent(in) nline, integer, intent(in) ncol, character(len=1), optional first_, character(len=1), optional last_)
This subroutine reads a 2D array of character values directly from a specified unit. The unit must be already opened and associated to the desired file. All the values to read must be written in `value` field of the text file that is between the two `|` (see the following box for an example of input text) and delimited by appropriate opening and closure delimiters.
 A Lot of usless stuff because only text between begin and end is read.
    begin 
       !Commented line
       KeywordField  | ValueField | !Comment two
    end
 Moreover the cursor needs to be before the first line of the array to be read. The procedure atomatically skeeps all the lines until the opening character. Opening and closing character may be specified as single character input, or left to the defult values that are `(` ande `)`, respectively. Avoid blank or commented lines inside the text array.
 The correct file syntax to read the 2x2 array `exArr`:
 exArr = \left[ \begin{array}{c c} Scrudge & DonaldDuck \\ Goofy & MickeyMouse \end{array} \right] 
 is:
    begin
       !Comment one
       exArr  | (Scrudge DonadDuck | !Comment two
              |  Goofy MikeyMouse) |
    end
 or equivalently:
    begin
       !Comment one
       exArr  |        | !Comment two
              | (Scrudge DonaldDuck |
              |  Goofy   MickeyMouse)|
    end
 so that each line in the text represnts a row of the vector output and coluns are space separated.
Parameters
in TheUnit the unit to be read.
in nline The number of rows of the 2D array
in ncol The number of columns of the 2D array
in first_ the opening delimiter of the array. Default is `(`
in last_ the closing delimiter of the array. Default is `)`
Author
Andrea Facci.
Definition at line 289 of file matrixRead2.f90.
References matrixread().
Referenced by readenv(), and readloads().
real(kind = prec) function, dimension(nline,ncol) dmatrixread (integer, intent(in) theUnit, integer, intent(in) nline, integer, intent(in) ncol, character(len=1), optional first_, character(len=1), optional last_)
This subroutine reads a 2D array of double precision values directly from a specified unit. The unit must be already opened and associated to the desired file. All the values to read must be written in `value` field of the text file that is between the two `|` (see the following box for an example of input text) and delimited by appropriate opening and closure delimiters.
 A Lot of usless stuff because only text between begin and end is read.
    begin 
       !Commented line
       KeywordField  | ValueField | !Comment two
    end
 Moreover the cursor needs to be before the first line of the array to be read. The procedure atomatically skeeps all the lines until the opening character. Opening and closing character may be specified as single character input, or left to the defult values that are `(` ande `)`, respectively. Avoid blank or commented lines inside the text array.
 The correct file syntax to read the 2x2 array `exArr`:
 exArr = \left[ \begin{array}{c c} 1.1 & 1.2 \\ 2.1 & 2.2 \end{array} \right] 
 is:
    begin
       !Comment one
       exArr  | (1.1 1.2 | !Comment two
              |  2.1 2.2)|
    end
 or equivalently:
    begin
       !Comment one
       exArr  |        | !Comment two
              | (1.1 1.2 |
              |  2.1 2.2)|
    end
 so that each line in the text represnts a row of the vector output and coluns are space separated.
Parameters
in TheUnit the unit to be read.
in nline The number of rows of the 2D array
in ncol The number of columns of the 2D array
in first_ the opening delimiter of the array. Default is `(`
in last_ the closing delimiter of the array. Default is `)`
Author
Andrea Facci.
Definition at line 86 of file matrixRead2.f90.
References matrixread().
Referenced by readboiler(), readchillers(), readelstorage(), readenv(), readgeneral(), readloads(), readpv(), readsc(), readtrigen(), and readwind().
integer function, dimension(nline,ncol) imatrixread (integer, intent(in) theUnit, integer, intent(in) nline, integer, intent(in) ncol, character(len=1), optional first_, character(len=1), optional last_)
This subroutine reads a 2D array of integer values directly from a specified unit. The unit must be already opened and associated to the desired file. All the values to read must be written in `value` field of the text file that is between the two `|` (see the following box for an example of input text) and delimited by appropriate opening and closure delimiters.
 A Lot of usless stuff because only text between begin and end is read.
    begin 
       !Commented line
       KeywordField  | ValueField | !Comment two
    end
 Moreover the cursor needs to be before the first line of the array to be read. The procedure atomatically skeeps all the lines until the opening character. Opening and closing character may be specified as single character input, or left to the defult values that are `(` ande `)`, respectively. Avoid blank or commented lines inside the text array.
 The correct file syntax to read the 2x2 array `exArr`:
 exArr = \left[ \begin{array}{c c} 11 & 12 \\ 21 & 22 \end{array} \right] 
 is:
    begin
       !Comment one
       exArr  | (11 12 | !Comment two
              |  21 22)|
    end
 or equivalently:
    begin
       !Comment one
       exArr  |        | !Comment two
              | (11 12 |
              |  21 22)|
    end
 so that each line in the text represnts a row of the vector output and coluns are space separated.
Parameters
in TheUnit the unit to be read.
in nline The number of rows of the 2D array
in ncol The number of columns of the 2D array
in first_ the opening delimiter of the array. Default is `(`
in last_ the closing delimiter of the array. Default is `)`
Author
Andrea Facci.
Definition at line 188 of file matrixRead2.f90.
References matrixread().
character(len=100) function, dimension(nline) matrixread (integer, intent(in) theUnit, integer, intent(in) nline, character(len=1), optional first_, character(len=1), optional last_)
This subroutine reads a 2D array of directly from a specified unit. This procedure does not associate the elements of the text array to any data type. On the contrary each line in the text array is associated to a row of a character type row vector, as it is. All the values to read must be written in `value` field of the text file that is between the two `|` (see the following box for an example of input text) and delimited by appropriate opening and closure delimiters.
 A Lot of usless stuff because only text between begin and end is read.
    begin 
       !Commented line
       KeywordField  | ValueField | !Comment two
    end
 The unit must be already opened and associated to the desired file. Moreover the cursor needs to be before the first line of the array to be read. The procedure atomatically skeeps all the lines until the opening character. Opening and closing character may be specified as single character input, or left to the defult values that are `(` and `)`, respectively. Avoid blank or commented lines inside the text array.
Parameters
in TheUnit the unit to be read.
in nline The number of rows of the 2D array
in first_ the opening delimiter of the array. Default is `(`
in last_ the closing delimiter of the array. Default is `)`
Author
Andrea Facci.
Definition at line 364 of file matrixRead2.f90.
References rewunit().
Referenced by cmatrixread(), dmatrixread(), imatrixread(), and readloads().