/home/Codici/Blink/FortranCode/src/matrixRead.f90 File Reference
Functions/Subroutines
real(kind(1.d0)) function,
*
dimension(nline, ncol) dmatrixread (theUnit, nline, ncol, first_, last_)
integer function, dimension(nline,
*
ncol) imatrixread (theUnit, nline, ncol, first_, last_)
character(len=100) function,
*
dimension(nline, ncol) cmatrixread (theUnit, nline, ncol, first_, last_)
character(len=100) function,
*
dimension(nline) matrixread (theUnit, nline, first_, last_)
Function/Subroutine Documentation
character(len=100) function, dimension(nline,ncol) cmatrixread (integer, intent(in) theUnit, integer, intent(in) nline, integer, intent(in) ncol, character(len=1), optional first_, character(len=1), optional last_)
Definition at line 153 of file matrixRead.f90.
References rewunit().
Referenced by cmatrixread(), and readloads().
real(kind(1.d0)) function, dimension(nline,ncol) dmatrixread (integer, intent(in) theUnit, integer, intent(in) nline, integer, intent(in) ncol, character(len=1), optional first_, character(len=1), optional last_)
Definition at line 34 of file matrixRead.f90.
References rewunit().
Referenced by dmatrixread(), readboiler(), readchillers(), readloads(), and readtrigen().
integer function, dimension(nline,ncol) imatrixread (integer, intent(in) theUnit, integer, intent(in) nline, integer, intent(in) ncol, character(len=1), optional first_, character(len=1), optional last_)
Definition at line 93 of file matrixRead.f90.
References rewunit().
Referenced by imatrixread().
character(len=100) function, dimension(nline) matrixread (integer, intent(in) theUnit, integer, intent(in) nline, character(len=1), optional first_, character(len=1), optional last_)
Definition at line 213 of file matrixRead.f90.
References rewunit().
Referenced by cmatrixread(), dmatrixread(), imatrixread(), matrixread(), and readloads().