/home/Progetti/Siat/Ottimizzatore/src/objFunction.f90 File Reference
Objective function.
Functions/Subroutines
real(kind=prec) function objfunction (c, t, obj)
Objective function.
Detailed Description
Author
Definition in file objFunction.f90.
Function/Subroutine Documentation
real(kind = prec) function objfunction (integer, dimension(nm), intent(in) c, integer, intent(in) t, character(len=*), intent(in) obj)
Returns the value of the objective function for a given plant state, time step and optimization criterion. This procedure accounts only for functions that are local in time, that is, that are function only of the plant state at time t and not at time > t, neither at time < t.
Parameters
in obj the optimization criterion.
in c index of the given set-point to be given as input. Defines the state of the plant $sp(i) = sp(c\_(i))$
in t time step index. Note t=x meas the x'th time step from the
Definition at line 39 of file objFunction.f90.
References economy::currcost(), and energy::pec().
Referenced by graphtools::graphpoints(), and graphtools::graphpointslocalmin().