/home/Codici/Blink/PowerManager/src/output.f90 File Reference
Print the output.
Functions/Subroutines
subroutine output (setPoint, postProcessing, path)
subroutine preparefile (u, nome, folder)
Detailed Description
Print the output. Andrea Facci.
Definition in file output.f90.
Function/Subroutine Documentation
subroutine output (integer, dimension(0:ntime+1,nm), intent(in) setPoint, logical, intent(in) postProcessing, character(len=*), intent(in) path)
Definition at line 31 of file output.f90.
References energy::chprod(), energy::elprod(), energy::elstoragelevelupdate(), energy::energyinput(), economy::firecost(), energy::fuelcons(), economy::fuelcost(), globalresults::globchrev(), globalresults::globcost(), globalresults::globelrev(), globalresults::globfirecost(), globalresults::globfuelcost(), globalresults::globmaintcost(), globalresults::globpec(), globalresults::globprofit(), globalresults::globrevenues(), globalresults::globthrev(), economy::grideconomy(), economy::maintenancecost(), energy::pec(), energy::pecpenalty(), preparefile(), energy::thprod(), and energy::thstoragelevelupdate().
Referenced by main(), and warning().
subroutine preparefile (integer, intent(in) u, character(len=*), intent(in) nome, character(len=*), intent(in) folder)
Definition at line 628 of file output.f90.
Referenced by output().