/home/Progetti/Siat/Ottimizzatore/src/readBoiler.f90 File Reference
Reads Boiler.inp file.
Functions/Subroutines
subroutine readboiler
Reads Boiler.inp file.
Detailed Description
Reads ThermalStorage.inp file.
Reads ElectricalStorage.inp file.
Author
Andrea Facci.
Definition in file readBoiler.f90.
Function/Subroutine Documentation
subroutine readboiler ()
This subroutine reads the file `Boilers.inp`. The procedure looks for each specific entry in the `keyword field`, and associates the value in the `value` field, to the corresponding variable. If the desired entry is not present returns an error message and aborts the execution. The structure of the input file is clarified in the following example along with the meaning of `keyword` and `value` field.
 A Lot of usless stuff because only text between begin and end is read.
    begin 
       !Commented line
       KeywordField  | ValueField | !Comment two

       KeywordField  | ValueField |
       ScalarValue   | 1          |
       Vector        | 1 2 n      |
       VectorSeries  |(a b c ) (d e f)|
       Matrix        |(11 12 13  |
                     | 21 22 23  |
                     | 31 32 33) |
    end
 A lof really usless text
 Note that only the text between `begin` and `end` is read. Blank lines are automatically discarded, while any unrecognized entry is discarded returning a warning code. Line beginning with `!` are considered comments and discarded.
Author
Andrea Facci.
Definition at line 61 of file readBoiler.f90.
References abortexecution(), allocatevar(), dmatrixread(), hcount(), ifindentry(), readkeyword(), rewunit(), myarithmetic::rnan(), and vcount().
Referenced by main().