/home/andrea/Desktop/FortranCodeBW/src/readKeyword.f90 File Reference
Reads a line of a text file.
Functions/Subroutines
subroutine readkeyword (theUnit, rew, keyword, value, error, nRow)
Reads a line of a text file.
Detailed Description
Author
Andrea Facci.
Definition in file readKeyword.f90.
Function/Subroutine Documentation
subroutine readkeyword (integer, intent(in) theUnit, logical, intent(in), optional rew, character(len=100), intent(out) keyword, character(len=100), intent(out) value, integer, intent(out), optional error, integer, intent(out), optional nRow)
This procedure reads a line of a unit and returns the `keyword` and `value` fileds as single value charaters of maximum lenght = 100. The Unit needs to be already opened and associated to the desired file. This subroutine reads the line corresponding to the actual position of te cursor. The structure expected for the input text file is clarified in the following example along with the meaning of `keyword` and `value` field.
 A Lot of usless stuff because only text between begin and end is read.
    begin 
       !Commented line
       KeywordField  | ValueField | !Comment two

       KeywordField  | ValueField |
       ScalarValue   | 1          |
       Vector        | 1 2 n      |
       VectorSeries  |(a b c ) (d e f)|
       Matrix        |(11 12 13  |
                     | 21 22 23  |
                     | 31 32 33) |
    end
 A lof really usless text
 Note that only the text between `begin` and `end` is read. Blank lines are automatically discarded, as well as lines beginning with `!` that are considered comments. If only one delimiter `|` is present the line is considered mispelled, no value are is associated to keyword nor to value, and an optional error code is returned. The number of lines that were read before the first valid line can be returned with the optional argument `nRow`. If the optional argument `rew` is set to true the unit is rewinded exactly of nRow lines at the end of the procedure.
Parameters
out Keyword,value keyword and value fields
out error Error code = 1 in case of mispelled lines
out nRow The number of lines that were read before the first valid line
in theUnit Unit number associated to the desired file.
in rew Wether to rewind or not the unit. Default is false.
Author
Andrea Facci.
Definition at line 71 of file readKeyword.f90.
References rewunit().
Referenced by readboiler(), readchillers(), readgeneral(), and readtrigen().