/home/Progetti/Siat/Ottimizzatore/src/rewUnit.f90 File Reference
rewind a unit.
Functions/Subroutines
subroutine rewunit (theUnit, n)
rewind a unit.
Detailed Description
Author
Definition in file rewUnit.f90.
Function/Subroutine Documentation
subroutine rewunit (integer, intent(in) theUnit, integer, intent(in) n)
Rewinds a unit for a specified number of lines. Note that the unit needs to be opened.
Parameters
in theUnit The Unit to be rewinded.
in n The number of lines to rewind.
Author
Definition at line 38 of file rewUnit.f90.
Referenced by findentry(), matrixread(), readboiler(), readchillers(), readelstorage(), readenv(), readgeneral(), readkeyword(), readloads(), readpv(), readsc(), readtrigen(), readwind(), and vcount().