/home/andrea/Desktop/FortranCodeBW/src/vCount.f90 File Reference
Counts the lines of a text matrix.
Functions/Subroutines
integer function vcount (theUnit, rew_, first_, last_)
Counts the lines of a text matrix.
Detailed Description
Author
Definition in file vCount.f90.
Function/Subroutine Documentation
integer function vcount (integer, intent(in) theUnit, logical, optional rew_, character(len=1), intent(in), optional first_, character(len=1), intent(in), optional last_)
This subroutine determines the number of lines between the two array delimiters. The unit must be already opened and associated to the desired file. All the values to read must be written in `value` field of the text file that is between the two `|` (see the following box for an example of input text) and delimited by appropriate opening and closure delimiters.
 A Lot of usless stuff because only text between begin and end is read.
    begin 
       !Commented line
       KeywordField  | ValueField | !Comment two
    end
 Moreover the cursor needs to be before the first line of the array to be read. The procedure atomatically skeeps all the lines until the opening character. Opening and closing character may be specified as single character input, or left to the defult values that are `(` ande `)`, respectively. Avoid blank or commented lines inside the text array.
 The correct file syntax to read the 2x2 array `exArr`:
 exArr = \left[ \begin{array}{c c} 1.1 & 1.2 \\ 2.1 & 2.2 \end{array} \right] 
 is:
    begin
       !Comment one
       exArr  | (1.1 1.2 | !Comment two
              |  2.1 2.2)|
    end
 or equivalently:
    begin
       !Comment one
       exArr  |        | !Comment two
              | (1.1 1.2 |
              |  2.1 2.2)|
    end
 so that each line in the text represnts a row of the vector output and coluns are space separated.
Parameters
in theUnit The unit associated to the file to be read
in rew_ Weather to rewind or not the unit at the end. Default is false.
in first_,last_ Opening and closing characters of the array.
Author
Definition at line 80 of file vCount.f90.
References rewunit().
Referenced by readboiler(), readchillers(), readloads(), and readtrigen().